### ISSUE TITLE
Add "Contact Us" page.

### ISSUE THREAD

**Issue by guillermoandrae** [hrphp/portal#39]
Add a page with contact information.

**Comment by troy0820** [comment]
Is this a new controller or a action on the indexcontroller? What is actually going on before I try to take a crack at this?

**Comment by guillermoandrae** [comment]
It'd be a new controller. Each page should have its own controller.

**Comment by troy0820** [comment]
Still learning this ZF2 thing.  It may take a while. All help is appreciated. 

Thanks :+1:
