### ISSUE TITLE
Add Hold Fast anchor.

### ISSUE THREAD

**Issue by guillermoandrae** [hrphp/portal#59]
Should link to: http://www.craftysnorfolk.com/holdfast/

**Comment by troy0820** [comment]
Do you want this in the footer with the other social stuff?

**Comment by guillermoandrae** [comment]
Yep.

**Comment by guillermoandrae** [comment]
Here it is, by the way: 
![anchor-solid-white](https://cloud.githubusercontent.com/assets/133861/6483271/11033242-c23d-11e4-8984-0351a233c003.png)

**Comment by troy0820** [comment]
Yeah, send me the image lol.
