### ISSUE TITLE
Add people to HRphp organization with logo 

### ISSUE THREAD

**Issue by troy0820** [hrphp/portal#82]
For github primarily but maybe even contributors on the site.....  Just an option.

**Comment by guillermoandrae** [comment]
Can you expound on this a little more? I don't know what you mean.

**Comment by troy0820** [comment]
For instance, Facebook is an organization, Dominion is an organization where people can be added to. I think only the person who owns the HRPHP organization can add people to it. Check out Norfolk.js and code for America's GitHub page and look at the organization's members.

**Comment by guillermoandrae** [comment]
So you just mean add people to our organization. No problem. I got confused by your inclusion of the words "with logo".

**Comment by guillermoandrae** [comment]
I've invited everyone that has contributed.
